[package]
name = "rust-ibkr"
version = "0.1.0"
authors = ["Andrew Cho <andrew.cho1992@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.15.0"
glob = "0.2"

